### ISSUE TITLE
Support fastq.gz

### ISSUE THREAD

**Issue by chmille4** [chmille4/taxonomer.iobio#11]
The only blocker for .gz support is partialstream.js. Need to add support for it, which would dramatically cut down on upload/transfer time.

Might be a little trickier for local file with mate pairs since this would require fq2fa to take two websocket streams, which minion currently doesn't support

**Comment by yiq** [comment]
As it is difficult ( for me at least ) to identify record boundary within a compressed stream, you might not have any choice other than decompress it first. Consequently, you might just need to put gunzip and gzip at the beginning and end of the current partialstream.js to make it work with fastq.gz. Hack you might just add gzip regardless since fq2fa supports gz stream seamlessly.

**Comment by chmille4** [comment]
partialStream now supports gzip'd streams. Local gzip files is still unsupported b\c of some issue with gzip streams coming from the client
